import { Analyst } from '../agents/analyst.js';
import { Skeptic } from '../agents/skeptic.js';
import { Researcher } from '../agents/researcher.js';
import { Strategist } from '../agents/strategist.js';
import { Validator } from '../agents/validator.js';
import fs from 'fs/promises';
import path from 'path';

export class Orchestrator {
  private analyst = new Analyst();
  private skeptic = new Skeptic();
  private researcher = new Researcher();
  private strategist = new Strategist();
  private validator = new Validator();

  async validateIdea(idea: string) {
    console.log(`\n[Orchestrator] 🎯 "${idea}" 정밀 검증 가동...`);

    // 1. Analyst: 데이터 중심 시장 분석
    const analysis = await this.analyst.analyze(idea);

    // 2. Skeptic: 비판적 공격 (분석 결과의 허점을 찾아내도록 유도)
    console.log("[Orchestrator] Skeptic에게 분석 보고서의 약점을 찾으라고 지시 중...");
    const risks = await this.skeptic.challenge(analysis);

    // 3. Researcher: 확장성 및 피봇 (리스크가 크다면 다른 길을 찾으라고 지시)
    console.log("[Orchestrator] Researcher에게 리스크를 우회할 대안을 찾으라고 지시 중...");
    const expansion = await this.researcher.explore(idea, `${analysis}\n\nRisks Identified: ${risks}`);

    // 4. Strategist: 비즈니스 모델 (현실적인 돈의 흐름 설계)
    const strategy = await this.strategist.designModel(idea, analysis, risks);

    // 5. Validator: 종합 판정 및 점수화
    const allOpinions = `
--- ANALYST REPORT ---
${analysis}

--- SKEPTIC CHALLENGE ---
${risks}

--- RESEARCHER INSIGHTS ---
${expansion}

--- STRATEGIST PLAN ---
${strategy}
    `;
    const verdict = await this.validator.judge(idea, allOpinions);

    // 6. 결과 기록 및 저장
    const result = {
      idea,
      timestamp: new Date().toISOString(),
      analysis,
      risks,
      expansion,
      strategy,
      verdict,
    };

    await this.saveToMemory(result);
    const reportPath = await this.saveReport(idea, result);

    return { idea, reportPath, verdict };
  }

  private async saveToMemory(result: any) {
    const memoryPath = path.join(process.cwd(), 'memory', 'ideas.json');
    try {
      const data = await fs.readFile(memoryPath, 'utf-8');
      const ideas = JSON.parse(data);
      ideas.push({
        id: Date.now(),
        idea: result.idea,
        verdictSummary: result.verdict.substring(0, 200) + '...',
        timestamp: result.timestamp
      });
      await fs.writeFile(memoryPath, JSON.stringify(ideas, null, 2));
    } catch (e) {
      console.warn("[Orchestrator] 메모리 저장 실패 (무시하고 진행)");
    }
  }

  private async saveReport(idea: string, data: any): Promise<string> {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const fileName = `deep_report_${timestamp}.md`;
    const filePath = path.join(process.cwd(), 'products', 'reports', fileName);

    const content = `
# 🔬 IDEAV Deep Validation Report
## Idea: ${idea}
**Generated at:** ${new Date().toLocaleString()}

---

## 📊 Market Analysis (Analyst-01)
${data.analysis}

---

## 🔥 Stress Test (Skeptic-99)
${data.risks}

---

## 🔍 Pivot & Growth Path (Researcher)
${data.expansion}

---

## 💰 Monetization Strategy (Strategist)
${data.strategy}

---

## ⚖️ Final Executive Verdict (Validator)
${data.verdict}

---
*This report is generated by AI Validation Lab. All scores and metrics are AI estimations.*
    `;

    await fs.writeFile(filePath, content, 'utf-8');
    return filePath;
  }
}
